## ********************************************************************* ##
## Copyright 2016-2018                                                   ##
## Portland Community College                                            ##
##                                                                       ##
## This file is part of Open Resources for Community College Algebra     ##
## (ORCCA).                                                              ##
## ********************************************************************* ##


#######################
# DO NOT EDIT THIS FILE
#######################

#   1) Make a copy of Makefile.paths.original
#      as Makefile.paths, which git will ignore.
#   2) Edit Makefile.paths to provide full paths to the root folders
#      of your local clones of the project repository and the mathbook
#      repository as described below.
#   3) The files Makefile and Makefile.paths.original
#      are managed by git revision control and any edits you make to
#      these will conflict. You should only be editing Makefile.paths.

##############
# Introduction
##############

# This is not a "true" makefile, since it does not
# operate on dependencies.  It is more of a shell
# script, sharing common configurations

######################
# System Prerequisites
######################

#   install         (system tool to make directories)
#   xsltproc        (xml/xsl text processor)
#   xmllint         (only to check source against DTD)
#   <helpers>       (PDF viewer, web browser, pager, Sage executable, etc)

#####
# Use
#####

#	A) Navigate to the location of this file
#	B) At command line:  make <some-target-from-the-options-below>

##################################################
# The included file contains customized versions
# of locations of the principal components of this
# project and names of various helper executables
##################################################
include Makefile.paths

###################################
# These paths are subdirectories of
# the project distribution
###################################
PRJSRC    = $(PRJ)/src
IMAGESSRC = $(PRJSRC)/images
OUTPUT    = $(PRJ)/output
PUB       = $(PRJ)/publication
STYLE     = $(PRJ)/style
XSL       = $(PRJ)/xsl

# The project's main hub file
MAINFILE  = $(PRJSRC)/orcca.ptx

# The project's styling files
PUBFILE   = $(PUB)/publication.xml
CSS       = $(STYLE)/css/orcca.css
PRJXSL    = $(PRJ)/xsl
LATEX     = $(XSL)/orcca-latex.xsl

# These paths are subdirectories of
# the Mathbook XML distribution
# MBUSR is where extension files get copied
# so relative paths work properly
MBXSL = $(MB)/xsl
MBUSR = $(MB)/user
DTD   = $(MB)/schema/dtd

# These paths are subdirectories of the output
# folder for different output formats
PGOUT      = $(OUTPUT)/pg
HTMLOUT    = $(OUTPUT)/html
PDFOUT     = $(OUTPUT)/pdf
IMAGESOUT  = $(OUTPUT)/images
WWOUT      = $(OUTPUT)/webwork-representations

# Some aspects of producing these examples require a WeBWorK server.
# For all but trivial testing or examples, please look into setting
# up your own WeBWorK server, or consult Alex Jordan about the use
# of PCC's server in a nontrivial capacity.    <alex.jordan@pcc.edu>
SERVER = "(https://webwork.pcc.edu,orcca,orcca,anonymous,orcca)"
#SERVER = http://localhost

webwork-representations:
	install -d $(WWOUT)
	-rm -r $(WWOUT)
	install -d $(WWOUT)
	$(MB)/pretext/pretext -vv -a -c webwork -d $(WWOUT) -s $(SERVER) $(MAINFILE)



pg:
	install -d $(PGOUT)
	cd $(PGOUT); \
	rm -r ORCCA; \
	xsltproc --xinclude --stringparam publisher $(PUBFILE) --stringparam chunk.level 2 $(MBXSL)/pretext-ww-problem-sets.xsl $(MAINFILE)

lanepdf:
	install -d $(OUTPUT)
	-rm -r $(PDFOUT) || :
	install -d $(PDFOUT)
	install -d $(PDFOUT)/images
	install -d $(IMAGESOUT)
	install -d $(IMAGESSRC)
	cp -a $(WWOUT)/*.png $(PDFOUT)/images || :
	cp -a $(IMAGESSRC) $(PDFOUT) || :
	cd $(PDFOUT); \
	xsltproc --xinclude --stringparam publisher $(PUBFILE) --stringparam toc.level 2 --stringparam latex.print 'yes' --stringparam latex.pageref 'no' --stringparam latex.sides 'two' --stringparam latex.geometry 'total={6.5in,8in}'  --stringparam exercise.inline.hint no --stringparam exercise.inline.answer no --stringparam exercise.inline.solution yes --stringparam exercise.divisional.hint no --stringparam exercise.divisional.answer no --stringparam exercise.divisional.solution no $(XSL)/orcca-latex.xsl $(MAINFILE) > orcca.tex; \
	echo 'PATCHES TO MAKE TEX COMPILE WITHOUT ERROR'; \
	perl -pi -e 's/(?<!\\)(\\3)/\\\1/' orcca.tex; \
	perl -pi -e 's/(?<!\\)\\(\\end)/\1/' orcca.tex; \
	echo 'GLOBAL PATCHES AFFECTING IMAGE WIDTH'; \
	for i in {1..16}; do perl -p0i -e 's/^(\\begin{exercisegroupcol}\{[234]\}\n(((?!exercisegroup).)*\n)*?\\begin{sidebyside}\{1\})\{0\.3\}\{0\.3\}\{0\}%\n(\\begin{sbspanel})\{0\.4\}/\1\{0\}\{0\}\{0\}%\n\4\{1\}/gm' orcca.tex; done; \
	echo 'GLOBAL PATCHES REMOVING ANSWER BLANKS'; \
	perl -p0i -e 's/(\\\(((?!\\\)).)*)(=|\\approx)( *}?\\\)) *\\fillin{[\d\.]*?}(%?\n)/\1\4\5/g' orcca.tex; \
	perl -pi -e 's/(\\\(((?!\\\)).)*)(=|\\approx)( *{?}?}?\\\)) *\\fillin{[\d\.]*?}\.?(%?)/\1\4\5/g' orcca.tex; \
	perl -pi -e 's/(\\\(((?!\\\)).)*\\\)) *= *\\fillin{[\d\.]*?}(%?)/\1\3/g' orcca.tex; \
	perl -p0i -e 's/\\par\n\\fillin\{.*?\}. *\\fillin\{.*?\}%\n//g' orcca.tex; \
	perl -p0i -e 's/(\\par\n.*[WH].*?\?) ?\\fillin{[\d\.]*}(%?\n)/\1\2/g' orcca.tex; \
	perl -p0i -e 's/\\par\n\\fillin{[\d\.]*} ?or ?\\fillin{[\d\.]*}%\n//g' orcca.tex; 
	perl -p0i -e 's/\\par\nAn equation for this line in point-slope form is: \\fillin{[\d\.]*}.%\n\\par\nAn equation for this line in slope-intercept form is: \\fillin{[\d\.]*}.%\n//g' orcca.tex; \
	perl -p0i -e 's/\\par\nIn slope-intercept form: \\fillin{[\d\.]*}%\n//g' orcca.tex; \
	perl -p0i -e 's/\\par\nLine .* in point-slope form is \\fillin{[\d\.]*}%\n\\par\nLine .* in slope-intercept form is \\fillin{[\d\.]*}%\n//g' orcca.tex; \
	perl -p0i -e 's/\\par\nFrom 11\\slash{}1 to 11\\slash{}5, the stock price.s percentage change was approximately \\fillin{4.090909090909091}.%//g' orcca.tex; \
	perl -pi -e 's/This line.s slope-intercept equation is \\fillin{6.363636363636363}.%/Find the slope-intercept equation of this line./g' orcca.tex; \
	perl -p0i -e 's/\\par\nReduced \\\(((?!\\\)).)*\\\)%\n//g' orcca.tex; \
	perl -p0i -e 's/\\par\nAxis of symmetry: \\fillin{[\d\.]*}%\n\\par\nVertex: \\fillin{[\d\.]*}%\n//g' orcca.tex; \
	perl -p0i -e 's/\\par\n\\\(y\\\)-intercept: \\fillin{[\d\.]*}%\n\\par\n\\\(x\\\)-intercept\(s\): \\fillin{[\d\.]*}%\n//g' orcca.tex; \
	perl -pi -e 's/^(\\\(\w*\\\)) has domain \\fillin{[\d\.]*} and range \\fillin{[\d\.]*}\.%/What are the domain and range of \1?/g' orcca.tex; \
	perl -p0i -e 's/\\par\n\\\(\\displaystyle{ \\text{area}}\\\) square feet%\n//g' orcca.tex; \
	perl -p0i -e 's/\\par\n\\\(\\displaystyle{ \\text{area}}\\\) square meters%\n//g' orcca.tex; \
	perl -p0i -e 's/\\par\n\\\(\\displaystyle{ \\text{new annual income}}\\\) dollars%\n//g' orcca.tex; \
	perl -p0i -e 's/\\par\nThe rectangle.s height is \\fillin\{\d\}\.%\n\\par\nThe rectangle.s base is \\fillin\{5\}\.%\n//g' orcca.tex; \
	perl -p0i -e 's/\\par\nYou should expand the original lot by \\fillin{4.090909090909091} in four directions.%\n//g' orcca.tex; \
	perl -pi -e 's/(\\item\{\}Solve \\\(d\(t\)=\{\d\}\\\) for \\\(t\\\)\.)  \\\(t\\\)%/\1%/g' orcca.tex; \
	perl -p0i -e 's/\\\(\\displaystyle{ f\(x\) }\\\)%//g' orcca.tex; \
	perl -p0i -e 's/\\par\nThe function.s domain is \\fillin{5.454545454545454}.%\n\\par\nThe function.s range is \\fillin{5.454545454545454}.%\n//g' orcca.tex; \
	perl -p0i -e 's/\\par\n\\fillin{2.272727272727273} and \\fillin{1.818181818181818}%\n//' orcca.tex; \
	perl -p0i -e 's/\\par\n\\\(\w\(-?\d+\){}\\\)%\n//g' orcca.tex; \
	perl -p0i -e 's/\\par\nIn set-builder notation, the solution set is \\fillin{[\d\.]*}\.\%\n\\par\nIn interval notation, the solution set is \\fillin{[\d\.]*}\.%\n/\\par\nExpress the solution set in both interval notation and set-builder notation./g' orcca.tex; \
	perl -p0i -e 's/\\par\n\\\(\\displaystyle{ \\sqrt\[\d+\]\{\d+} }\\\)\\\(\\displaystyle{\\cdot \\sqrt\[\d+\]{\(}}\\\) \\fillin{0.454545454545455} \\\(\\displaystyle{\)}\\\)%//g' orcca.tex; \
	perl -p0i -e 's/\\par\n\\\(\w \\\)%\n//g' orcca.tex; \
	perl -p0i -e 's/\\par\nIf there are no \\\(x\\\)-intercepts, enter \\mono{NONE}\. If there are more than one, use commas to separate the points\.%\n//g' orcca.tex; \
	perl -p0i -e 's/\\begin{enumerate}.*\n\\item{}The \\\(y\\\)-intercept is .*%\n\\item{}The \\\(x\\\)-intercept\(s\).*\n\\end{enumerate}.*\n/\\par\nFind the \\\(y\\\)-intercept and the \\\(x\\\)-intercept(s)\.%\n/g' orcca.tex; \
	perl -p0i -e 's/\\item{}The vertex is \\fillin{9.090909090909092}.%\n\\item{}The \\\(y\\\)-intercept is \\fillin\{[\d\.]*}\.%\n\\item{}The \\\(x\\\)-intercept\(s\) is\\slash{}are \\fillin{[\d\.]*}\.%\n/\\item{}The vertex is \\fillin{9.090909090909092}.%\n\\item{}Find the \\\(y\\\)-intercept\.%\n\\item{}Find the \\\(x\\\)-intercept\(s\)\.%\n/g' orcca.tex; \
	perl -p0i -e 's/\\par\n\\\(F\\\) is in \\fillin{9.090909090909092}%\n//g' orcca.tex; \
	perl -p0i -e 's/\\par\nThe range is \\fillin{9.090909090909092}.%\n//' orcca.tex; \
	perl -p0i -e 's/(?<=\.) \\\(T\(x\)\\\)%\n//' orcca.tex; \
	echo 'GLOBAL PATCHES OF CONTENT'; \
	perl -pi -e 's/\\textbackslash{}(\\textdollar{})/\1/g' orcca.tex; \
	perl -pi -e 's/\[\\textasciigrave{}([^\]]*?)\\textasciigrave{}\]/\\\(\1\\\)/g' orcca.tex; \
	perl -pi -e "s/(\d)'',/\1,/g" orcca.tex; \
	perl -p0i -e 's/\\par\nUse interval notation. If you need to write a union of intervals, use \\mono{U} for the union symbol.%\n//g' orcca.tex; \
	perl -p0i -e 's/\\par\nExpress the solution set in both interval notation and set-builder notation.//g' orcca.tex; \
	perl -p0i -e 's/\\par\nIf you need to use a square root, .*\n//' orcca.tex; \
	echo 'PATCHES EDITING FRONTMATTER'; \
	perl -pi -e 's/2019-2020/2019–2020/' orcca.tex; \
	echo 'PATCHES EDITING CHAPTER 1'; \
	perl -pi -e 's/2\.5 - 8\.2/2.5 \\cdot 8.2/' orcca.tex; \
	perl -pi -e 's/3\.2 - 0\.039/3.2 \\cdot 0.039/' orcca.tex; \
	perl -p0i -e 's/\\begin{sidebyside}.*\n.*\n.*?webwork-181-image-1.*/\\begin{sidebyside}{1}{0.2}{0.2}{0}%\n\\begin{sbspanel}{0.6}%\n\\includegraphics[width=\\linewidth]{images\/webwork-181-image-1.png}/' orcca.tex; \
	perl -p0i -e 's/\\begin{sidebyside}.*\n.*\n.*?webwork-183-image-1.*/\\begin{sidebyside}{1}{0.2}{0.2}{0}%\n\\begin{sbspanel}{0.6}%\n\\includegraphics[width=\\linewidth]{images\/webwork-183-image-1.png}/' orcca.tex; \
	echo 'PATCHES EDITING CHAPTER 2'; \
	perl -p0i -e 's/(Evaluate each algebraic expression for the given value\(s\):%\n\\par\n.*):.*/\1/g' orcca.tex; \
	perl -p0i -e 's/\\begin{sidebyside}.*\n.*\n.*?webwork-1030-image-1.*/\\begin{sidebyside}{1}{0}{0}{0}%\n\\begin{sbspanel}{1}%\n\\includegraphics[width=\\linewidth]{images\/webwork-1030-image-1.png}/' orcca.tex; \
	perl -p0i -e 's/\\begin{sidebyside}.*\n.*\n.*?webwork-1031-image-1.*/\\begin{sidebyside}{1}{0}{0}{0}%\n\\begin{sbspanel}{1}%\n\\includegraphics[width=\\linewidth]{images\/webwork-1031-image-1.png}/' orcca.tex; \
	perl -p0i -e 's/\\begin{sidebyside}.*\n.*\n.*?webwork-1228-image-1.*/\\begin{sidebyside}{1}{0}{0}{0}%\n\\begin{sbspanel}{1}%\n\\includegraphics[width=\\linewidth]{images\/webwork-1228-image-1.png}/' orcca.tex; \
	perl -p0i -e 's/\\begin{sidebyside}.*\n.*\n.*?webwork-1229-image-1.*/\\begin{sidebyside}{1}{0}{0}{0}%\n\\begin{sbspanel}{1}%\n\\includegraphics[width=\\linewidth]{images\/webwork-1229-image-1.png}/' orcca.tex; \
	echo 'PATCHES EDITING CHAPTER 3'; \
	perl -p0i -e 's/\\par\n\\textbraceleft{} x \\textbar{} x \\textgreater{} 4 \\textbraceright{}; \\fillin{6.818181818181818}%\n//' orcca.tex; \
	echo 'PATCHES EDITING CHAPTER 4'; \
	perl -pi -e 's/^(minutes since the experiment started, the gas had a mass of 215.6 grams.%)/Six \1/' orcca.tex; \
	perl -pi -e 's/^(minutes since the experiment started, the gas had a mass of 156.8 grams.%)/Eighteen \1/' orcca.tex; \
	echo 'PATCHES EDITING CHAPTER 5'; \
	perl -pi -e 's/These two companies would charge the same amount on a monthly bill when the talk time was \\fillin{4.545454545454546} minutes.%/After how many minutes would these two companies charge the same amount on a monthly bill?/g' orcca.tex; \
	echo 'PATCHES EDITING CHAPTER 6'; \
	perl -p0i -e 's/(\\begin{divisionexerciseegcol}.*\n)Expand.*square.*of.*a.*bi.*nomial\.%\n\\par\n/\1/g' orcca.tex; \
	perl -p0i -e 's/(\\textbf{Perfect Square Trinomial Formula}\\space\\space)%\n/\1 Expand the square of a binomial.%\n/' orcca.tex; \
	perl -p0i -e 's/\\par\n\\\(\\displaystyle{B}\\\) square units%\n//g' orcca.tex; \
	perl -p0i -e 's/\\par\n\\\(\\displaystyle{h}\\\) units%\n//g' orcca.tex; \
	perl -p0i -e 's/(\\\(\\displaystyle{    \({a[\+\-]\db}.*)= \n(}\\\))\\fillin.*%\n/\1\2%\n/g' orcca.tex; \
	perl -pi -e 's/\({7a-9b}\)\^2 = /\({7a-9b}\)\^2/' orcca.tex; \
	perl -pi -e 's/\({8a\+6b}\)\^2 = /\({8a+6b}\)\^2/' orcca.tex; \
	echo 'PATCHES EDITING CHAPTER 7'; \
	perl -p0i -e 's/\\begin{sidebyside}.*\n.*\n.*?webwork-3498-image-1.*/\\begin{sidebyside}{1}{0.31}{0.31}{0}%\n\\begin{sbspanel}{0.38}%\n\\includegraphics[width=\\linewidth]{images\/webwork-3498-image-1.png}/' orcca.tex; \
	perl -p0i -e 's/\\begin{sidebyside}.*\n.*\n.*?webwork-3498-image-2.*/\\begin{sidebyside}{1}{0.31}{0.31}{0}%\n\\begin{sbspanel}{0.38}%\n\\includegraphics[width=\\linewidth]{images\/webwork-3498-image-2.png}/' orcca.tex; \
	perl -p0i -e 's/\\begin{sidebyside}.*\n.*\n.*?webwork-3720-image-1.*/\\begin{sidebyside}{1}{0.17}{0.17}{0}%\n\\begin{sbspanel}{0.66}%\n\\includegraphics[width=\\linewidth]{images\/webwork-3720-image-1.png}/' orcca.tex; \
	perl -p0i -e 's/\\begin{sidebyside}.*\n.*\n.*?webwork-3721-image-1.*/\\begin{sidebyside}{1}{0.17}{0.17}{0}%\n\\begin{sbspanel}{0.66}%\n\\includegraphics[width=\\linewidth]{images\/webwork-3721-image-1.png}/' orcca.tex; \
	perl -pi -e 's/^\\textbackslash{}\[([^\]]*)\\textbackslash{}\]%/\\\[\1\\\]/' orcca.tex; \
	perl -p0i -e 's/\\par\n8 in\.; \\fillin.*\n//' orcca.tex; \
	perl -p0i -e 's/\\par\n8 ft\.; 15 ft\.; \\fillin.*\n//' orcca.tex; \
	echo 'PATCHES EDITING CHAPTER 8'; \
	perl -p0i -e 's/(Simplifying Rational Expressions with More Than One Variable)%\n(Simplify this expression.%)/\1: \2/' orcca.tex; \
	perl -pi -e 's/\\textbackslash{}frac\\textbraceleft{}3x-6\\textbraceright{}\\textbraceleft{}x\\textasciicircum{}\\textbraceleft{}2\\textbraceright{}-x-2\\textbraceright{}.%/\\\(\\frac{3x-6}{x^2-x-2}\\\).%/' orcca.tex; \
	perl -p0i -e 's/\\par\n9 hours; \\fillin{6.818181818181818} hours%//' orcca.tex; \
	echo 'PATCHES EDITING CHAPTER 9'; \
	perl -p0i -e 's/\\begin{figureptx}{Pythagorean Theorem Problem}{p:figure:RKB}{}%\n\\begin{image}{0.25}{0.5}{0.25}%/\\begin{figureptx}{Pythagorean Theorem Problem}{p:figure:RKB}{}%\n\\begin{image}{0.375}{0.25}{0.375}%/' orcca.tex; \
	perl -p0i -e 's/\\par\nThere should be two solutions:%\n\\par\nWhen the width is \\fillin{3.636363636363636} feet, the length is \\fillin{3.636363636363636} feet.%\n\\par\nWhen the width is \\fillin{3.636363636363636} feet, the length is \\fillin{3.636363636363636} feet.%\n/\\par\nThere should be two solutions.\n/g' orcca.tex; \
	echo 'PATCHES EDITING CHAPTER 10'; \
	perl -p0i -e 's/\\par\nThe function.s domain in this context is \\fillin{[\d\.]*}.%\n\\par\nThe function.s range in this context is \\fillin{[\d\.]*}.%\n//g' orcca.tex; \
	echo 'PATCHES EDITING CHAPTER 11'; \
	echo 'PATCHES EDITING CHAPTER 12'; \
	perl -p0i -e 's/\\begin{exercisegroupcol}\{4}\n\\begin{divisionexerciseegcol}\{1}{}{}{p:exercise:mJP}%/\\begin{exercisegroupcol}\{3}\n\\begin{divisionexerciseegcol}\{1}{}{}{p:exercise:mJP}%/' orcca.tex; \
	perl -p0i -e 's/\\begin{divisionexerciseegcol}\{39}{}{}{g:exercise:idm364094098688}%\n\\\(\{6} \\lt \\frac\{2 }\{7 }x \\lt \{16}\\\)%\n\\end{divisionexerciseegcol}%\n\\begin{divisionexerciseegcol}\{40}{}{}{g:exercise:idm364093579504}%\n\\\(\{6} \\lt \\frac\{3 }\{7 }x \\lt \{21}\\\)%\n\\end{divisionexerciseegcol}%\n\\begin{divisionexerciseegcol}\{41}{}{}{g:exercise:idm364093579280}%\n\\\(\{22} \\gt -3 - \\frac\{5 }\{2 }x \\geq \{-18}\\\)%\n\\end{divisionexerciseegcol}%\n\\begin{divisionexerciseegcol}\{42}{}{}{g:exercise:idm364093599040}%\n\\\(\{9} \\gt -1 - \\frac\{5 }\{6 }x \\geq {-21}\\\)%\n\\end{divisionexerciseegcol}%\n/\\begin{divisionexerciseegcol}\{39}{}{}{g:exercise:idm364094098688}%\nSolve the compound inequality algebraically.%\n\\par\n\\\(\{6} \\lt \\frac\{2 }\{7 }x \\lt \{16}\\\)%\n\\end{divisionexerciseegcol}%\n\\begin{divisionexerciseegcol}\{40}{}{}{g:exercise:idm364093579504}%\nSolve the compound inequality algebraically.%\n\\par\n\\\(\{6} \\lt \\frac\{3 }\{7 }x \\lt \{21}\\\)%\n\\end{divisionexerciseegcol}%\n\\begin{divisionexerciseegcol}\{41}{}{}{g:exercise:idm364093579280}%\nSolve the compound inequality algebraically.%\n\\par\n\\\(\{22} \\gt -3 - \\frac\{5 }\{2 }x \\geq \{-18}\\\)%\n\\end{divisionexerciseegcol}%\n\\begin{divisionexerciseegcol}\{42}{}{}{g:exercise:idm364093599040}%\nSolve the compound inequality algebraically.%\n\\par\n\\\(\{9} \\gt -1 - \\frac\{5 }\{6 }x \\geq {-21}\\\)%\n\\end{divisionexerciseegcol}%\n/' orcca.tex; \
	perl -pi -e 's/Write answer/Write the answer/' orcca.tex; \
	echo 'PATCHES EDITING CHAPTER 14'; \
	perl -p0i -e 's/(\\begin{exercisegroupcol}\{2}\n\\begin{divisionexerciseegcol}\{35}{}{}{p:exercise:ooY}%)/\\par\\medskip\\noindent%\n\1/' orcca.tex; \
	echo 'PAGE BREAKING'; \
	perl -p0i -e 's/(\\begin{inlineexercise}{}{p:exercise:Iqg}%\n.*\n.*\n.*\n)(.*\n.*\n.*\n.*\n.*\n)/\1\\begin{multicols}{3}\2\\end{multicols}\n/' orcca.tex; \
	perl -p0i -e 's/(\\begin{inlineexercise}{.*?}{p:exercise:lCJ}%\n.*\n.*\n.*\n)(.*\n.*\n.*\n.*\n.*\n.*\n)/\1\\begin{multicols}{4}\2\\end{multicols}\n/' orcca.tex; \
	perl -p0i -e 's/(\\begin.*RJS}%\n.*\n.*\n.*\n).*\n/\1\\begin{multicols}{4}\n/' orcca.tex; \
	perl -p0i -e 's/(\\begin{inlineexercise}{.*?}{p:exercise:dYk}%\n.*\n.*\n.*\n)(.*\n.*\n.*\n.*\n.*\n.*\n)/\1\\begin{multicols}{4}\2\\end{multicols}\n/' orcca.tex; \
	perl -p0i -e 's/(\\noindent.*idm363683663152.*\n)(.*\n.*\n.*\n.*\n.*\n.*\n)/\1\\begin{multicols}{4}\2\\end{multicols}\n/' orcca.tex; \
	perl -p0i -e 's/(\\begin{inlineexercise}{.*?}{p:exercise:iId}%\n.*\n.*\n.*\n)(.*\n.*\n.*\n.*\n)/\1\\begin{multicols}{2}\2\\end{multicols}\n/' orcca.tex; \
	perl -p0i -e 's/(\\begin.*idm363685636544.*\n.*\n.*\n.*\n)(.*\n.*\n.*\n.*\n)/\1\\begin{multicols}{2}\2\\end{multicols}\n/' orcca.tex; \
	perl -p0i -e 's/(\\begin.*idm363685922240.*\n.*\n.*\n.*\n)(.*\n.*\n.*\n.*\n)/\1\\begin{multicols}{2}\2\\end{multicols}\n/' orcca.tex; \
	perl -p0i -e 's/(\\begin.*idm363686404448}%\n.*\n).*\n/\1\\begin{multicols}{4}\n/' orcca.tex; \
	perl -pi -e 's/(\\begin{inlineexercise}{}{p:exercise:NTG}%)/\\newpage\1/' orcca.tex; \
	perl -pi -e 's/(\\begin{inlineexercise}{}{p:exercise:ahY}%)/\\newpage\1/' orcca.tex; \
	perl -pi -e 's/(To visualize the difference between)/\\newpage\n\1/' orcca.tex; \
	perl -pi -e 's/(\\textbf{Types of Numbers}\\space\\space%)/\\newpage\n\1/' orcca.tex; \
	perl -pi -e 's/(\\begin{example}{}{p:example:Xcw}%)/\\newpage\n\1/' orcca.tex; \
	xelatex orcca.tex; \
	xelatex orcca.tex; \
	xelatex orcca.tex; \


odd-answers:
	cd $(PRINTOUT); \
	xsltproc --xinclude --stringparam publisher $(PUBFILE) --stringparam toc.level 3 --stringparam latex.pageref 'no' --stringparam latex.sides 'one' $(XSL)/orcca-odd-answers.xsl $(MAINFILE) > orcca-odd-answers.tex; \
	xelatex orcca-odd-answers.tex; \
	xelatex orcca-odd-answers.tex; \
	xelatex orcca-odd-answers.tex;

#	echo 'GLOBAL SPACING'; \
#	echo 'Next line removes \leavevmode when it comes right before an enumerate'; \
#	perl -p0i -e 's/\\leavevmode%\n(\\begin{enumerate})/\1/g' orcca.tex; \
#	echo 'Next line removes \leavevmode when it comes right before a multicols'; \
#	perl -p0i -e 's/\\leavevmode%\n(\\begin{multicols})/\1/g' orcca.tex; \
#	echo 'Next line removes \par when it comes right before an equation'; \
#	perl -p0i -e 's/\\par\n(%\n\\begin\{equation)/\1/g' orcca.tex; \
#	echo 'Next two lines attempt to prevent pagebreaks after an "Explanation" title; not always with success'; \
#	perl -p0i -e 's/(\\noindent\\textbf\{Explanation\}.*?\n(((?!\\begin).)*?\n)*?)(.*\\par)/\\makeatletter\\\@beginparpenalty=10000\\makeatother\n\1\\makeatletter\\\@beginparpenalty=-51\\makeatother\n\4/g' orcca.tex; \
#	perl -p0i -e 's/(\\noindent\\textbf\{Explanation\}.*?\n(((?!\\par).)*?\n)*?\\end(?!({tikzpicture}|{aligned}|{alignedat})).*?\n)/\\makeatletter\\\@beginparpenalty=10000\\makeatother\n\1\\makeatletter\\\@beginparpenalty=-51\\makeatother\n/g' orcca.tex; \
#	echo 'Next line attempts to prevent pagebreaks after an "Exercises" starts; not always with success'; \
#	perl -p0i -e 's/(\\begin\{exercises-subsection\}\{Exercises\}.*?\n(.*?\n)*?\\end\{divisionexercise\}%\n)/\\makeatletter\\\@beginparpenalty=10000\\makeatother\n\1\\makeatletter\\\@beginparpenalty=-51\\makeatother\n/g' orcca.tex; \
#	echo 'Next two lines look for a list in an exercise where the exercise starts, and gets first line to start on exercise opening line'; \
#	perl -p0i -e 's/^(\\begin{divisionexerciseegcol}.*?\n\\begin{enumerate)(}\[label=\\alph\*\.)(\]\n)((.*?\n)*?\\end{enumerate)}/\1\*\2,itemjoin=\{\\vspace\{0\.5pc\}\\newline\},afterlabel=\{\\hspace\{1ex\}\}\3\4\*}\\vspace{0.5pc}\n\n/gm' orcca.tex; \
#	perl -p0i -e 's/^(\\begin{divisionexerciseegcol}.*?\n\\hypertarget{.*?}\{\}%\n\\begin{enumerate)(}\[label=\\alph\*\.)(\]\n)((.*?\n)*?\\end{enumerate)}/\1\*\2,itemjoin=\{\\vspace\{0\.5pc\}\\newline\},afterlabel=\{\\hspace\{1ex\}\}\3\4\*}\\vspace{0.5pc}\n\n/gm' orcca.tex; \
#	echo 'IMAGE WIDTH ADJUSTMENT'; \
#	echo 'WeBWorK images in a multicolumn list or exercisegroup need these sizing adjustments, effectively resizing them to 100%. The for loops are just to make the regex search and replace repeat enough times to hit all instances within a list or exerisegroup'; \
#	for i in {1..3}; do perl -p0i -e 's/^(\\begin{inlineexercise}.*?(((?!inlineexercise).)*\n)*?\\begin{multicols}\{3\}\n(((?!multicols).)*\n)*?\\begin{sidebyside}\{1\})\{0\.3\}\{0\.3\}\{0\}%\n(\\begin{sbspanel})\{0\.4\}/\1\{0\}\{0\}\{0\}%\n\6\{1\}/gm' orcca.tex; done; \
#	for i in {1..6}; do perl -p0i -e 's/^(\\begin{exercisegroup}\n(((?!exercisegroup).)*\n)*?\\begin{sidebyside}\{1\})\{0\.3\}\{0\.3\}\{0\}%\n(\\begin{sbspanel})\{0\.4\}/\1\{0\}\{0\}\{0\}%\n\4\{1\}/gm' orcca.tex; done; \
#	for i in {1..16}; do perl -p0i -e 's/^(\\begin{exercisegroupcol}\{[234]\}\n(((?!exercisegroup).)*\n)*?\\begin{sidebyside}\{1\})\{0\.3\}\{0\.3\}\{0\}%\n(\\begin{sbspanel})\{0\.4\}/\1\{0\}\{0\}\{0\}%\n\4\{1\}/gm' orcca.tex; done; \
#	perl -p0i -e 's/^(The pie chart represents a collector.s collection of signatures from various artists.%\n\\begin{sidebyside}\{1\}){0\.166666666666667}{0\.166666666666667}\{0\}%\n\\begin{sbspanel}{0\.666666666666667}/\1\{0\}\{0\}\{0\}%\n\\begin{sbspanel}\{1\}/gm' orcca.tex; \
#	perl -p0i -e 's/^((The pie chart .* artists.|The following is a nutrition .* box.|A community college .* the survey.)%\n\\begin{sidebyside}\{1\}){0\.166666666666667}{0\.166666666666667}\{0\}%\n\\begin{sbspanel}{0\.666666666666667}/\1\{0\}\{0\}\{0\}%\n\\begin{sbspanel}\{1\}/gm' orcca.tex; \
#	echo 'SYSTEMS OF EQUATIONS IN DISPLAY MODE'; \
#	for i in {1..20}; do perl -p0i -e 's/^(\\textbf{Using a Graph to Solve a System}\\space\\space%\nUse a graph to solve the system of equations.%\n\\begin{exercisegroupcol}\{\d\}\n(.*?\n)*?\\begin{divisionexerciseegcol}.*?\n(.*?\n)*?)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*})/\1\\begin{fleqn}\[1em\]\n\\leavevmode\\vspace\*\{-\\dimexpr\\baselineskip\+\\abovedisplayskip\\relax}\4\\end{fleqn}\\newline/m' orcca.tex; done; \
#	for i in {1..50}; do perl -p0i -e 's/^(\\textbf{Solving System of Equations Using Substitution}\\space\\space%\nSolve the following system of equations.%\n\\begin{exercisegroupcol}\{\d\}\n(.*?\n)*?\\begin{divisionexerciseegcol}.*?\n(.*?\n)*?)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*})/\1\\begin{fleqn}\[1em\]\n\\leavevmode\\vspace\*\{-\\dimexpr\\baselineskip\+\\abovedisplayskip\\relax}\4\\end{fleqn}\\newline/m' orcca.tex; done; \
#	for i in {1..32}; do perl -p0i -e 's/^(\\textbf{Solving System of Equations by Elimination}\\space\\space%\nSolve the following system of equations.%\n\\begin{exercisegroupcol}\{\d\}\n(.*?\n)*?\\begin{divisionexerciseegcol}.*?\n(.*?\n)*?)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*})/\1\\begin{fleqn}\[1em\]\n\\leavevmode\\vspace\*\{-\\dimexpr\\baselineskip\+\\abovedisplayskip\\relax}\4\\end{fleqn}\\newline/m' orcca.tex; done; \
#	for i in {1..8}; do perl -p0i -e 's/^(\\textbf{Solving Systems of Linear Equations by Graphing}\\space\\space%\nUse a graph to solve the system of equations.%\n\\begin{exercisegroupcol}\{\d\}\n(.*?\n)*?\\begin{divisionexerciseegcol}.*?\n(.*?\n)*?)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*})/\1\\begin{fleqn}\[1em\]\n\\leavevmode\\vspace\*\{-\\dimexpr\\baselineskip\+\\abovedisplayskip\\relax}\4\\end{fleqn}\\newline/m' orcca.tex; done; \
#	for i in {1..8}; do perl -p0i -e 's/^(\\textbf{Substitution}\\space\\space%\nSolve the following system of equations.%\n\\begin{exercisegroupcol}\{\d\}\n(.*?\n)*?\\begin{divisionexerciseegcol}.*?\n(.*?\n)*?)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*})/\1\\begin{fleqn}\[1em\]\n\\leavevmode\\vspace\*\{-\\dimexpr\\baselineskip\+\\abovedisplayskip\\relax}\4\\end{fleqn}\\newline/m' orcca.tex; done; \
#	for i in {1..8}; do perl -p0i -e 's/^(\\textbf{Elimination}\\space\\space%\nSolve the following system of equations.%\n\\begin{exercisegroupcol}\{\d\}\n(.*?\n)*?\\begin{divisionexerciseegcol}.*?\n(.*?\n)*?)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*})/\1\\begin{fleqn}\[1em\]\n\\leavevmode\\vspace\*\{-\\dimexpr\\baselineskip\+\\abovedisplayskip\\relax}\4\\end{fleqn}\\newline/m' orcca.tex; done; \
#	perl -p0i -e 's/^(\\begin{example}[^\n]*?example:VQz}%\n.*?\n.*?\n.*?\n)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*}\n)%\n\\item\{\}%\n(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*}\n)/\1\\begin{fleqn}\[1em\]\n\2\\end{fleqn}\n%\n\\item\{\}%\n\\begin{fleqn}\[1em\]\n\4\\end{fleqn}\n/m' orcca.tex; \
#	echo 'INDIVIDUAL INSERTIONS'; \
#	echo 'Redefine sectionptx to address aside side effect'; \
#	perl -p0i -e 's/^(\\NewDocumentEnvironment{sectionptx}{mmmmmm}\n{%\n\\renewcommand{\\divisionnameptx}{Section}%\n\\renewcommand{\\titleptx}\{..}%\n\\renewcommand{\\subtitleptx}\{..\}%\n\\renewcommand{\\shortitleptx}\{..\}%\n\\renewcommand{\\authorsptx}\{..\}%\n\\renewcommand{\\epigraphptx}\{..\}%\n\\section\[..\]\{..\}%\n\\label\{..\}%\n\}\{)(\}%\n)/\1\n\n\2/m' orcca.tex; \
#	echo 'SHORTEN UNRESOLVED XREF WARNINGS'; \
#	perl -pi -e 's/\{\(\(\(Unresolved xref, reference "[\w\-]*"; check spelling or use "provisional" attribute\)\)\)\}\\hyperlink\{\}\{(\w*?)~\}/\1 A.B/g' orcca.tex; \
#	perl -pi -e 's/\{\(\(\(Unresolved xref, reference "[\w\-]*"; check spelling or use "provisional" attribute\)\)\)\}(\w*?)~/\1 A.B/g' orcca.tex; \
#	perl -pi -e 's/\{\(\(\(Unresolved xref, reference "[\w\-]*"; check spelling or use "provisional" attribute\)\)\)\}\\hyperlink\{\}{(.*?)}/\1/g' orcca.tex; \
#	echo 'REMOVE ALL ANSWER BLANKS AND EQUALS SIGNS THAT ARE IN SHORT LINES LIKE 1+2=___ '; \
#	perl -pi -e 's/^(\\\(((?!\\\)).)*) *=([ }]*\\\)) *\\fillin{\d+} *\.?%\n/\1\3%\n/g' orcca.tex; \
#	perl -pi -e 's/^(\\item\{\}\\\(((?!\\\)).)*) *=([ }]*\\\)) *\\fillin{\d+} *\.?%\n/\1\3%\n/g' orcca.tex; \
#	perl -pi -e 's/^(\\\(((?!\\\)).)*\\\)) *= *\\fillin{\d+} *\.?%\n/\1%\n/g' orcca.tex; \
#	perl -pi -e 's/^(\\item\{\}\\\(((?!\\\)).)*\\\)) *= *\\fillin{\d+} *\.?%\n/\1%\n/g' orcca.tex; \
#	perl -pi -e 's/^(\\\(((?!\\\)).)*) *\\approx([ }]*\\\)) *\\fillin{\d+} *\.?%\n/\1\3%\n/g' orcca.tex; \
#	perl -pi -e 's/^(\\\(((?!\\\)).)*) *=\{\}([ }]*\\\)) *\\fillin\{\d+\} *\.?%\n/\1\3%\n/g' orcca.tex; \

lanepdfold:
	install -d $(OUTPUT)
	-rm -r $(PDFOUT) || :
	install -d $(PDFOUT)
	install -d $(PDFOUT)/images
	install -d $(IMAGESOUT)
	install -d $(IMAGESSRC)
	-rm $(PDFOUT)/images/*
	-rm $(PDFOUT)/*.*
# 	cp -a $(IMAGESOUT) $(PDFOUT)
# 	cp -a $(WWOUT)/*0-image-*.png $(PDFOUT)/images
# 	cp -a $(WWOUT)/*1-image-*.png $(PDFOUT)/images
# 	cp -a $(WWOUT)/*2-image-*.png $(PDFOUT)/images
# 	cp -a $(WWOUT)/*3-image-*.png $(PDFOUT)/images
# 	cp -a $(WWOUT)/*4-image-*.png $(PDFOUT)/images
# 	cp -a $(WWOUT)/*5-image-*.png $(PDFOUT)/images
# 	cp -a $(WWOUT)/*6-image-*.png $(PDFOUT)/images
# 	cp -a $(WWOUT)/*7-image-*.png $(PDFOUT)/images
# 	cp -a $(WWOUT)/*8-image-*.png $(PDFOUT)/images
# 	cp -a $(WWOUT)/*9-image-*.png $(PDFOUT)/images
	cd $(WWOUT); \
	rsync -r --include='*.png' --exclude='*' . $(PDFOUT)/images
	cp -a $(IMAGESSRC) $(PDFOUT)
	cd $(PDFOUT); \
	xsltproc -xinclude --stringparam publisher $(PUBFILE) --stringparam toc.level 2 --stringparam latex.print 'yes' --stringparam latex.pageref 'no' --stringparam latex.sides 'two' --stringparam latex.geometry 'total={6.5in,8in}'  --stringparam exercise.inline.hint no --stringparam exercise.inline.answer no --stringparam exercise.inline.solution yes --stringparam exercise.divisional.hint no --stringparam exercise.divisional.answer no --stringparam exercise.divisional.solution no $(PRJXSL)/orcca-latex.xsl $(MAINFILE) > orcca.tex; \
	echo 'GLOBAL SPACING'; \
	echo 'Next line removes \leavevmode when it comes right before an enumerate'; \
	perl -p0i -e 's/\\leavevmode%\n(\\begin{enumerate})/\1/g' orcca.tex; \
	echo 'Next line removes \leavevmode when it comes right before a multicols'; \
	perl -p0i -e 's/\\leavevmode%\n(\\begin{multicols})/\1/g' orcca.tex; \
	echo 'Next line removes \par when it comes right before an equation'; \
	perl -p0i -e 's/\\par\n(%\n\\begin\{equation)/\1/g' orcca.tex; \
	echo 'Next two lines attempt to prevent pagebreaks after an "Explanation" title; not always with success'; \
	perl -p0i -e 's/(\\noindent\\textbf\{Explanation\}.*?\n(((?!\\begin).)*?\n)*?)(.*\\par)/\\makeatletter\\\@beginparpenalty=10000\\makeatother\n\1\\makeatletter\\\@beginparpenalty=-51\\makeatother\n\4/g' orcca.tex; \
	perl -p0i -e 's/(\\noindent\\textbf\{Explanation\}.*?\n(((?!\\par).)*?\n)*?\\end(?!({tikzpicture}|{aligned}|{alignedat})).*?\n)/\\makeatletter\\\@beginparpenalty=10000\\makeatother\n\1\\makeatletter\\\@beginparpenalty=-51\\makeatother\n/g' orcca.tex; \
	echo 'Next line attempts to prevent pagebreaks after an "Exercises" starts; not always with success'; \
	perl -p0i -e 's/(\\begin\{exercises-subsection\}\{Exercises\}.*?\n(.*?\n)*?\\end\{divisionexercise\}%\n)/\\makeatletter\\\@beginparpenalty=10000\\makeatother\n\1\\makeatletter\\\@beginparpenalty=-51\\makeatother\n/g' orcca.tex; \
	echo 'Next two lines look for a list in an exercise where the exercise starts, and gets first line to start on exercise opening line'; \
	perl -p0i -e 's/^(\\begin{divisionexerciseegcol}.*?\n\\begin{enumerate)(}\[label=\\alph\*\.)(\]\n)((.*?\n)*?\\end{enumerate)}/\1\*\2,itemjoin=\{\\vspace\{0\.5pc\}\\newline\},afterlabel=\{\\hspace\{1ex\}\}\3\4\*}\\vspace{0.5pc}\n\n/gm' orcca.tex; \
	perl -p0i -e 's/^(\\begin{divisionexerciseegcol}.*?\n\\hypertarget{.*?}\{\}%\n\\begin{enumerate)(}\[label=\\alph\*\.)(\]\n)((.*?\n)*?\\end{enumerate)}/\1\*\2,itemjoin=\{\\vspace\{0\.5pc\}\\newline\},afterlabel=\{\\hspace\{1ex\}\}\3\4\*}\\vspace{0.5pc}\n\n/gm' orcca.tex; \
	echo 'IMAGE WIDTH ADJUSTMENT'; \
	echo 'WeBWorK images in a multicolumn list or exercisegroup need these sizing adjustments, effectively resizing them to 100%. The for loops are just to make the regex search and replace repeat enough times to hit all instances within a list or exerisegroup'; \
	for i in {1..3}; do perl -p0i -e 's/^(\\begin{inlineexercise}.*?(((?!inlineexercise).)*\n)*?\\begin{multicols}\{3\}\n(((?!multicols).)*\n)*?\\begin{sidebyside}\{1\})\{0\.3\}\{0\.3\}\{0\}%\n(\\begin{sbspanel})\{0\.4\}/\1\{0\}\{0\}\{0\}%\n\6\{1\}/gm' orcca.tex; done; \
	for i in {1..6}; do perl -p0i -e 's/^(\\begin{exercisegroup}\n(((?!exercisegroup).)*\n)*?\\begin{sidebyside}\{1\})\{0\.3\}\{0\.3\}\{0\}%\n(\\begin{sbspanel})\{0\.4\}/\1\{0\}\{0\}\{0\}%\n\4\{1\}/gm' orcca.tex; done; \
	for i in {1..16}; do perl -p0i -e 's/^(\\begin{exercisegroupcol}\{[234]\}\n(((?!exercisegroup).)*\n)*?\\begin{sidebyside}\{1\})\{0\.3\}\{0\.3\}\{0\}%\n(\\begin{sbspanel})\{0\.4\}/\1\{0\}\{0\}\{0\}%\n\4\{1\}/gm' orcca.tex; done; \
	perl -p0i -e 's/^(The pie chart represents a collector.s collection of signatures from various artists.%\n\\begin{sidebyside}\{1\}){0\.166666666666667}{0\.166666666666667}\{0\}%\n\\begin{sbspanel}{0\.666666666666667}/\1\{0\}\{0\}\{0\}%\n\\begin{sbspanel}\{1\}/gm' orcca.tex; \
	perl -p0i -e 's/^((The pie chart .* artists.|The following is a nutrition .* box.|A community college .* the survey.)%\n\\begin{sidebyside}\{1\}){0\.166666666666667}{0\.166666666666667}\{0\}%\n\\begin{sbspanel}{0\.666666666666667}/\1\{0\}\{0\}\{0\}%\n\\begin{sbspanel}\{1\}/gm' orcca.tex; \
	echo 'SYSTEMS OF EQUATIONS IN DISPLAY MODE'; \
	for i in {1..20}; do perl -p0i -e 's/^(\\textbf{Using a Graph to Solve a System}\\space\\space%\nUse a graph to solve the system of equations.%\n\\begin{exercisegroupcol}\{\d\}\n(.*?\n)*?\\begin{divisionexerciseegcol}.*?\n(.*?\n)*?)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*})/\1\\begin{fleqn}\[1em\]\n\\leavevmode\\vspace\*\{-\\dimexpr\\baselineskip\+\\abovedisplayskip\\relax}\4\\end{fleqn}\\newline/m' orcca.tex; done; \
	for i in {1..50}; do perl -p0i -e 's/^(\\textbf{Solving System of Equations Using Substitution}\\space\\space%\nSolve the following system of equations.%\n\\begin{exercisegroupcol}\{\d\}\n(.*?\n)*?\\begin{divisionexerciseegcol}.*?\n(.*?\n)*?)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*})/\1\\begin{fleqn}\[1em\]\n\\leavevmode\\vspace\*\{-\\dimexpr\\baselineskip\+\\abovedisplayskip\\relax}\4\\end{fleqn}\\newline/m' orcca.tex; done; \
	for i in {1..32}; do perl -p0i -e 's/^(\\textbf{Solving System of Equations by Elimination}\\space\\space%\nSolve the following system of equations.%\n\\begin{exercisegroupcol}\{\d\}\n(.*?\n)*?\\begin{divisionexerciseegcol}.*?\n(.*?\n)*?)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*})/\1\\begin{fleqn}\[1em\]\n\\leavevmode\\vspace\*\{-\\dimexpr\\baselineskip\+\\abovedisplayskip\\relax}\4\\end{fleqn}\\newline/m' orcca.tex; done; \
	for i in {1..8}; do perl -p0i -e 's/^(\\textbf{Solving Systems of Linear Equations by Graphing}\\space\\space%\nUse a graph to solve the system of equations.%\n\\begin{exercisegroupcol}\{\d\}\n(.*?\n)*?\\begin{divisionexerciseegcol}.*?\n(.*?\n)*?)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*})/\1\\begin{fleqn}\[1em\]\n\\leavevmode\\vspace\*\{-\\dimexpr\\baselineskip\+\\abovedisplayskip\\relax}\4\\end{fleqn}\\newline/m' orcca.tex; done; \
	for i in {1..8}; do perl -p0i -e 's/^(\\textbf{Substitution}\\space\\space%\nSolve the following system of equations.%\n\\begin{exercisegroupcol}\{\d\}\n(.*?\n)*?\\begin{divisionexerciseegcol}.*?\n(.*?\n)*?)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*})/\1\\begin{fleqn}\[1em\]\n\\leavevmode\\vspace\*\{-\\dimexpr\\baselineskip\+\\abovedisplayskip\\relax}\4\\end{fleqn}\\newline/m' orcca.tex; done; \
	for i in {1..8}; do perl -p0i -e 's/^(\\textbf{Elimination}\\space\\space%\nSolve the following system of equations.%\n\\begin{exercisegroupcol}\{\d\}\n(.*?\n)*?\\begin{divisionexerciseegcol}.*?\n(.*?\n)*?)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*})/\1\\begin{fleqn}\[1em\]\n\\leavevmode\\vspace\*\{-\\dimexpr\\baselineskip\+\\abovedisplayskip\\relax}\4\\end{fleqn}\\newline/m' orcca.tex; done; \
	perl -p0i -e 's/^(\\begin{example}[^\n]*?example:VQz}%\n.*?\n.*?\n.*?\n)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*}\n)%\n\\item\{\}%\n(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*}\n)/\1\\begin{fleqn}\[1em\]\n\2\\end{fleqn}\n%\n\\item\{\}%\n\\begin{fleqn}\[1em\]\n\4\\end{fleqn}\n/m' orcca.tex; \
	echo 'INDIVIDUAL INSERTIONS'; \
	echo 'Redefine sectionptx to address aside side effect'; \
	perl -p0i -e 's/^(\\NewDocumentEnvironment{sectionptx}{mmmmmm}\n{%\n\\renewcommand{\\divisionnameptx}{Section}%\n\\renewcommand{\\titleptx}\{..}%\n\\renewcommand{\\subtitleptx}\{..\}%\n\\renewcommand{\\shortitleptx}\{..\}%\n\\renewcommand{\\authorsptx}\{..\}%\n\\renewcommand{\\epigraphptx}\{..\}%\n\\section\[..\]\{..\}%\n\\label\{..\}%\n\}\{)(\}%\n)/\1\n\n\2/m' orcca.tex; \
	echo 'SHORTEN UNRESOLVED XREF WARNINGS'; \
	perl -pi -e 's/\{\(\(\(Unresolved xref, reference "[\w\-]*"; check spelling or use "provisional" attribute\)\)\)\}\\hyperlink\{\}\{(\w*?)~\}/\1 A.B/g' orcca.tex; \
	perl -pi -e 's/\{\(\(\(Unresolved xref, reference "[\w\-]*"; check spelling or use "provisional" attribute\)\)\)\}(\w*?)~/\1 A.B/g' orcca.tex; \
	perl -pi -e 's/\{\(\(\(Unresolved xref, reference "[\w\-]*"; check spelling or use "provisional" attribute\)\)\)\}\\hyperlink\{\}{(.*?)}/\1/g' orcca.tex; \
	echo 'REMOVE ALL ANSWER BLANKS AND EQUALS SIGNS THAT ARE IN SHORT LINES LIKE 1+2=___ '; \
	perl -pi -e 's/^(\\\(((?!\\\)).)*) *=([ }]*\\\)) *\\fillin{\d+} *\.?%\n/\1\3%\n/g' orcca.tex; \
	perl -pi -e 's/^(\\item\{\}\\\(((?!\\\)).)*) *=([ }]*\\\)) *\\fillin{\d+} *\.?%\n/\1\3%\n/g' orcca.tex; \
	perl -pi -e 's/^(\\\(((?!\\\)).)*\\\)) *= *\\fillin{\d+} *\.?%\n/\1%\n/g' orcca.tex; \
	perl -pi -e 's/^(\\item\{\}\\\(((?!\\\)).)*\\\)) *= *\\fillin{\d+} *\.?%\n/\1%\n/g' orcca.tex; \
	perl -pi -e 's/^(\\\(((?!\\\)).)*) *\\approx([ }]*\\\)) *\\fillin{\d+} *\.?%\n/\1\3%\n/g' orcca.tex; \
	perl -pi -e 's/^(\\\(((?!\\\)).)*) *=\{\}([ }]*\\\)) *\\fillin\{\d+\} *\.?%\n/\1\3%\n/g' orcca.tex; \
	xelatex orcca.tex; \
	xelatex orcca.tex; \
	xelatex orcca.tex; \


oldlanepdf:
	install -d $(OUTPUT)
	install -d $(PDFOUT)
	install -d $(PDFOUT)/images
	install -d $(IMAGESOUT)
	install -d $(IMAGESSRC)
	-rm $(PDFOUT)/images/*
	-rm $(PDFOUT)/*.*
	cp -a $(IMAGESOUT) $(PDFOUT)
	cp -a $(WWOUT)/*0-image-*.png $(PDFOUT)/images
	cp -a $(WWOUT)/*1-image-*.png $(PDFOUT)/images
	cp -a $(WWOUT)/*2-image-*.png $(PDFOUT)/images
	cp -a $(WWOUT)/*3-image-*.png $(PDFOUT)/images
	cp -a $(WWOUT)/*4-image-*.png $(PDFOUT)/images
	cp -a $(WWOUT)/*5-image-*.png $(PDFOUT)/images
	cp -a $(WWOUT)/*6-image-*.png $(PDFOUT)/images
	cp -a $(WWOUT)/*7-image-*.png $(PDFOUT)/images
	cp -a $(WWOUT)/*8-image-*.png $(PDFOUT)/images
	cp -a $(WWOUT)/*9-image-*.png $(PDFOUT)/images
	cp -a $(IMAGESSRC) $(PDFOUT)
	cd $(PDFOUT); \
	xsltproc -xinclude --stringparam exercise.inline.hint no --stringparam exercise.inline.answer no --stringparam exercise.inline.solution yes --stringparam exercise.divisional.hint no --stringparam exercise.divisional.answer no --stringparam exercise.divisional.solution no $(LATEX) $(OUTPUT)/merge.xml; \
		perl -pi -e 's/\%\% fontspec package will make Latin Modern \(lmodern\) the default font/\%\% Customized to load Palatino fonts\n\\usepackage[T1]{fontenc}\n\\renewcommand\{\\rmdefault\}\{zpltlf\} \%Roman font for use in math mode\n\\usepackage\[scaled=.85\]\{beramono\}\% used only by \\mathtt\n\\usepackage\[type1\]\{cabin\}\%used only by \\mathsf\n\\usepackage\{amsmath,amssymb,amsthm\}\%load before newpxmath\n\\usepackage\[varg,cmintegrals,bigdelims,varbb\]\{newpxmath\}\n\\usepackage\[scr=rsfso\]\{mathalfa\}\n\\usepackage\{bm\} \%load after all math to give access to bold math\n\% Now load the otf text fonts using fontspec--wont affect math\n\\usepackage\[no-math\]\{fontspec\}\n\\setmainfont\{TeXGyrePagellaX\}\n\\defaultfontfeatures\{Ligatures=TeX,Scale=1,Mapping=tex-text\}\n\% This is a palatino-like font\n\%\\setmainfont\[BoldFont = texgyrepagella-bold.otf, ItalicFont = texgyrepagella-italic.otf, BoldItalicFont = texgyrepagella-bolditalic.otf]\{texgyrepagella-regular.otf\}\n\\linespread\{1.02\}/' orcca.tex; \
	perl -pi -e 's/\\usepackage\{fontspec\}\n//' orcca.tex; \
	perl -pi -e 's/title={{Checkpoint/title={{\\includegraphics[height=1pc]{images\/webwork-logo.eps} Checkpoint/g' orcca.tex; \
perl -pi -e 's/\\usepackage\{geometry\}//' orcca.tex; \
perl -pi -e 's/\\documentclass\[10pt,\]\{book\}/\\documentclass\[paper=letter,DIV=14,BCOR=0.25in,chapterprefix,numbers=noenddot,fontsize=10pt,toc=indentunnumbered\]\{scrbook\}/' orcca.tex; \
perl -pi -e 's/\\geometry\{letterpaper,total=\{340pt,9\.0in\}\}//' orcca.tex; \
	echo 'Images in a multicolumn exercicegroup need their sizing adjusted to account for the narrower column'; \
	for i in {1..26}; do perl -p0i -e 's/(\\begin{exercisegroup}\{2\}\n(((?!exercisegroup).)*\n)*?\\begin{sidebyside}\{1\})\{0\.3\}\{0\.3\}\{0\}\n(\\begin{sbspanel})\{0\.4\}/\1\{0\.1\}\{0\.1\}\{0\}\n\4\{0\.8\}/g' orcca.tex; done; \
	for i in {1..26}; do perl -p0i -e 's/(\\begin{exercisegroup}\{2\}\n(((?!exercisegroup).)*\n)*?\\begin{sidebyside}\{1\})\{0\.16+7\}\{0\.16+7\}\{0\}\n(\\begin{sbspanel})\{0\.6+7\}/\1\{0\}\{0\}\{0\}\n\4\{1\}/g' orcca.tex; done; \
	for i in {1..26}; do perl -p0i -e 's/(\\begin{exercisegroup}\{3\}\n(((?!exercisegroup).)*\n)*?\\begin{sidebyside}\{1\})\{0\.3\}\{0\.3\}\{0\}\n(\\begin{sbspanel})\{0\.4\}/\1\{0\}\{0\}\{0\}\n\4\{1\}/g' orcca.tex; done ;\
	xelatex orcca.tex; \
xelatex orcca.tex; \
	xelatex orcca.tex

pdf:
	install -d $(OUTPUT)
	install -d $(PDFOUT)
	install -d $(PDFOUT)/images
	install -d $(IMAGESOUT)
	install -d $(IMAGESSRC)
	-rm $(PDFOUT)/images/*
	-rm $(PDFOUT)/*.*
	cp -a $(IMAGESOUT) $(PDFOUT)
	cp -a $(WWOUT)/*.png $(PDFOUT)/images
	cp -a $(IMAGESSRC) $(PDFOUT)
	cd $(PDFOUT); \
	xsltproc -xinclude --stringparam latex.fillin.style box --stringparam exercise.inline.hint no --stringparam exercise.inline.answer no --stringparam exercise.inline.solution yes --stringparam exercise.divisional.hint no --stringparam exercise.divisional.answer no --stringparam exercise.divisional.solution no $(LATEX) $(OUTPUT)/merge.xml; \
	perl -pi -e 's/\\usepackage\{geometry\}//' orcca.tex; \
	perl -pi -e 's/\\documentclass\[10pt,\]\{book\}/\\documentclass\[paper=letter,DIV=14,BCOR=0.25in,chapterprefix,numbers=noenddot,fontsize=10pt,toc=indentunnumbered\]\{scrbook\}/' orcca.tex; \
	perl -pi -e 's/\\geometry\{letterpaper,total=\{340pt,9\.0in\}\}//' orcca.tex; \
	perl -pi -e 's/\%\% fontspec package will make Latin Modern \(lmodern\) the default font/\%\% Customized to load Palatino fonts\n\\usepackage[T1]{fontenc}\n\\renewcommand\{\\rmdefault\}\{zpltlf\} \%Roman font for use in math mode\n\\usepackage\[scaled=.85\]\{beramono\}\% used only by \\mathtt\n\\usepackage\[type1\]\{cabin\}\%used only by \\mathsf\n\\usepackage\{amsmath,amssymb,amsthm\}\%load before newpxmath\n\\usepackage\[varg,cmintegrals,bigdelims,varbb\]\{newpxmath\}\n\\usepackage\[scr=rsfso\]\{mathalfa\}\n\\usepackage\{bm\} \%load after all math to give access to bold math\n\% Now load the otf text fonts using fontspec--wont affect math\n\\usepackage\[no-math\]\{fontspec\}\n\\setmainfont\{TeXGyrePagellaX\}\n\\defaultfontfeatures\{Ligatures=TeX,Scale=1,Mapping=tex-text\}\n\% This is a palatino-like font\n\%\\setmainfont\[BoldFont = texgyrepagella-bold.otf, ItalicFont = texgyrepagella-italic.otf, BoldItalicFont = texgyrepagella-bolditalic.otf]\{texgyrepagella-regular.otf\}\n\\linespread\{1.02\}/' orcca.tex; \
	perl -pi -e 's/\\usepackage\{fontspec\}\n//' orcca.tex; \
	perl -pi -e 's/Checkpoint/\\includegraphics[height=1pc]{images\/webwork-logo.eps} Checkpoint/g' orcca.tex; \
	perl -pi -e 's/(after-item-skip)=\\smallskipamount,(after-skip)=\\smallskipamount/\1=0pt,\2=0pt/' orcca.tex; \
	perl -pi -e 's/(\\end{exercisegroup})\\par\\medskip\\noindent\n/\1\n/' orcca.tex; \
	echo 'In sidebyside with multiple paragraphs, need to set the parskip to match rest of the book'; \
	perl -pi -e 's/(\\begin{sbspanel}.*)/\1\n\\setlength{\\parskip}{0.5pc}/g' orcca.tex; \
	echo 'In exercisegroup, when the problem starts with a sidebyside (tabular, image), pull it upward vertically'; \
	perl -p0i -e 's/(\\exercise\[\d+\.\] \\hypertarget{exercise-\d+}{}\n)(\\begin{sidebyside})/\1\\vspace{-\\dimexpr 2\\baselineskip\\relax}%\n\2/g' orcca.tex; \
	echo 'In exercisegroup, when the problem starts with an enumerate, pull it upward vertically'; \
	perl -p0i -e 's/(\\exercise\[\d+\.\] \\hypertarget{exercise-\d+}{}\n\\hypertarget{p-\d+}{}%\n)(\\leavevmode%\n\\begin{enumerate}\[[^\]]*\]\n[^\n]*\n[^\n]*fillin)/\1\\vspace{-\\dimexpr2\\parskip+1\\baselineskip-0.4pt\\relax}%\n%\2/g' orcca.tex; \
	perl -p0i -e 's/(\\exercise\[\d+\.\] \\hypertarget{exercise-\d+}{}\n\\hypertarget{p-\d+}{}%\n)(\\leavevmode%\n\\begin{enumerate})/\1\\vspace{-\\dimexpr\\parskip+1\\baselineskip\\relax}%\n%\2/g' orcca.tex; \
	perl -p0i -e 's/(\\exercise\[\d+\.\] \\hypertarget{exercise-\d+}{}\n\\hypertarget{p-\d+}{}%\n.*?\n)\\par\n(\\hypertarget{p-\d+}{}%\n)\\leavevmode%\n(\\begin{itemize})/\1\2\3/g' orcca.tex; \
	echo 'In an inline exercise, remove the vertical spacing prior to an enumerate'; \
	perl -p0i -e 's/(\\begin{inlineexercise}.*?\\label{exercise-\d+}\n(((?!inlineexercise).)*\n)*?)\\par\n(\\hypertarget{p-\d+}{}%\n)\\leavevmode%\n(\\begin{enumerate})/\1\4\5/g' orcca.tex; \
	perl -p0i -e 's/(\\begin{inlineexercise}.*?\\label{exercise-\d+}\n(((?!inlineexercise).)*\n)*?)\\par\\medskip\n(\\hypertarget{p-\d+}{}%\n)\\leavevmode%\n(\\begin{multicols})/\1\4\5/g' orcca.tex; \
	perl -p0i -e 's/(\\begin{inlineexercise}.*?\\label{exercise-\d+}\n(((?!inlineexercise).)*\n)*?)\\par\n(\\hypertarget{p-\d+}{}%\n)\\leavevmode%\n(\\begin{multicols})/\1\4\5/g' orcca.tex; \
	echo 'In an exercisegroup exercise, remove the vertical spacing prior to an enumerate'; \
	perl -p0i -e 's/(\\exercise\[\d+\.\].*?\\hypertarget{exercise-\d+}{}\n(((?!exercise).)*\n)*?)\\par\n(\\hypertarget{p-\d+}{}%\n)\\leavevmode%\n(\\begin{enumerate})/\1\4\5/g' orcca.tex; \
	echo 'In an divisional exercise, remove the vertical spacing prior to an enumerate'; \
	perl -p0i -e 's/(\\begin{divisionexercise}.*?\\hypertarget{exercise-\d+}{}\n(((?!divisionexercise).)*\n)*?)\\par\n(\\hypertarget{p-\d+}{}%\n)\\leavevmode%\n(\\begin{enumerate})/\1\4\5/g' orcca.tex; \
	echo 'In division exercise, when the problem starts with an enumerate, pull it upward vertically'; \
	perl -p0i -e 's/(\\begin{divisionexercise}{\d+}\\hypertarget{exercise-\d+}{}\n\\hypertarget{p-\d+}{}%\n)(\\leavevmode%\n\\begin{enumerate})/\1\\vspace{-\\dimexpr\\parskip+1\\baselineskip-0.4pt\\relax}%\n%\2/g' orcca.tex; \
	echo 'Images in a multicolumn exercicegroup need their sizing adjusted to account for the narrower column'; \
	for i in {1..26}; do perl -p0i -e 's/(\\begin{exercisegroup}\(2\)\n(((?!exercisegroup).)*\n)*?\\begin{sidebyside}\{1\})\{0\.3\}\{0\.3\}\{0\}\n(\\begin{sbspanel})\{0\.4\}/\1\{0\.1\}\{0\.1\}\{0\}\n\4\{0\.8\}/g' orcca.tex; done; \
	for i in {1..26}; do perl -p0i -e 's/(\\begin{exercisegroup}\(2\)\n(((?!exercisegroup).)*\n)*?\\begin{sidebyside}\{1\})\{0\.16+7\}\{0\.16+7\}\{0\}\n(\\begin{sbspanel})\{0\.6+7\}/\1\{0\}\{0\}\{0\}\n\4\{1\}/g' orcca.tex; done; \
	for i in {1..26}; do perl -p0i -e 's/(\\begin{exercisegroup}\(3\)\n(((?!exercisegroup).)*\n)*?\\begin{sidebyside}\{1\})\{0\.3\}\{0\.3\}\{0\}\n(\\begin{sbspanel})\{0\.4\}/\1\{0\}\{0\}\{0\}\n\4\{1\}/g' orcca.tex; done ;\
	echo 'Images in a multicolumn list within a webwork exercise need their sizing adjusted to account for the narrower column'; \
	perl -p0i -e 's/(\\begin{inlineexercise}.*?\\label{exercise-\d+}\n(((?!inlineexercise).)*\n)*?\\begin{multicols}\{3\}\n(((?!multicols).)*\n)*?[^\n]*\\begin{sidebyside}\{1\})\{0\.3\}\{0\.3\}\{0\}\n(\\begin{sbspanel})\{0\.4\}/\1\{0\}\{0\}\{0\}\n\6\{1\}/g' orcca.tex; \
	perl -p0i -e 's/(\\begin{inlineexercise}.*?\\label{exercise-\d+}\n(((?!inlineexercise).)*\n)*?\\begin{multicols}\{3\}\n(((?!multicols).)*\n)*?[^\n]*\\begin{sidebyside}\{1\})\{0\.3\}\{0\.3\}\{0\}\n(\\begin{sbspanel})\{0\.4\}/\1\{0\}\{0\}\{0\}\n\6\{1\}/g' orcca.tex; \
	perl -p0i -e 's/(\\begin{inlineexercise}.*?\\label{exercise-\d+}\n(((?!inlineexercise).)*\n)*?\\begin{multicols}\{3\}\n(((?!multicols).)*\n)*?[^\n]*\\begin{sidebyside}\{1\})\{0\.3\}\{0\.3\}\{0\}\n(\\begin{sbspanel})\{0\.4\}/\1\{0\}\{0\}\{0\}\n\6\{1\}/g' orcca.tex; \
	perl -p0i -e 's/(\\begin{divisionexercise}.*?\\hypertarget{exercise-\d+}{}\n(((?!divisionexercise).)*\n)*?\\begin{multicols}\{3\}\n(((?!multicols).)*\n)*?[^\n]*\\begin{sidebyside}\{1\})\{0\.3\}\{0\.3\}\{0\}\n(\\begin{sbspanel})\{0\.4\}/\1\{0\}\{0\}\{0\}\n\6\{1\}/g' orcca.tex; \
	perl -p0i -e 's/(\\begin{divisionexercise}.*?\\hypertarget{exercise-\d+}{}\n(((?!divisionexercise).)*\n)*?\\begin{multicols}\{3\}\n(((?!multicols).)*\n)*?[^\n]*\\begin{sidebyside}\{1\})\{0\.3\}\{0\.3\}\{0\}\n(\\begin{sbspanel})\{0\.4\}/\1\{0\}\{0\}\{0\}\n\6\{1\}/g' orcca.tex; \
	perl -p0i -e 's/(\\begin{divisionexercise}.*?\\hypertarget{exercise-\d+}{}\n(((?!divisionexercise).)*\n)*?\\begin{multicols}\{3\}\n(((?!multicols).)*\n)*?[^\n]*\\begin{sidebyside}\{1\})\{0\.3\}\{0\.3\}\{0\}\n(\\begin{sbspanel})\{0\.4\}/\1\{0\}\{0\}\{0\}\n\6\{1\}/g' orcca.tex; \
	perl -pi -e 's/\\noindent$/\\noindent%/g' orcca.tex; \
	perl -pi -e 's/^(\\hypertarget{exercisegroup-\d+}{})\n/\1%\n/' orcca.tex; \
	perl -pi -e 's/^(\\subparagraph\[{.*?}\]{)(.*?}\\hypertarget{exercisegroup-\d+}{})/\1\\hspace{-1em}\2/g' orcca.tex; \
	echo 'After an aside, put line breaks in tex source.'; \
	perl -pi -e 's/(\\end{aside}\n)/\1\\leavevmode%\n\n/' orcca.tex; \
	perl -pi -e 's/(The slope of this line is +\\fillin{\d+}.%)/\\vspace{-1pc}\n\n\1/g' orcca.tex; \
	perl -pi -e 's/(All rights reserved\.) /\1\n\n/' orcca.tex; \
	echo 'section-arithmetic-with-negative-numbers'; \
	perl -p0i -e 's/(\\typeout{\*+}\n\\typeout{Subsection 1\.1\.6 )/\\pagebreak\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-2}{})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-5}{})/\\pagebreak\n\n\1/' orcca.tex; \
	echo 'section-fractions-and-fraction-arithmetic'; \
	perl -pi -e 's/(^.*\\label{example-5})/\\pagebreak\n\1/' orcca.tex; \
	echo 'section-absolute-value-and-square-root'; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-19}{})/\\pagebreak\n\n\1/' orcca.tex; \
	echo 'section-order-of-operations'; \
	perl -pi -e 's/(^.*?\\label{exercise-227})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{solution-249}{})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{solution-254}{})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-26}{})/\\pagebreak\n\n\1/' orcca.tex; \
	echo 'section-comparison-symbols-and-notation-for-intervals'; \
	perl -pi -e 's/(^.*?\\label{exercise-367})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?\\label{exercises-6})/\\pagebreak\n\n\1/' orcca.tex; \
	echo 'review-basic-math-review'; \
	perl -pi -e 's/(\\begin{example}.*?\\label{example-2[123456]}\n)/\1\\leavevmode\n/g' orcca.tex; \
	perl -pi -e 's/(\\begin{example}.*?\\label{example-23})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-37}{})/\\pagebreak\n\n\1/' orcca.tex; \
	echo 'section-variables-and-evaluating-expressions'; \
	perl -pi -e 's/(^.*?\\hypertarget{solution-481}{})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{solution-495}{})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -pi -e 's/(\\exercise)(\[8\.\] \\hypertarget{exercise-494}{})/\1\*\2/' orcca.tex; \
	echo 'section-geometry-formulas'; \
	perl -pi -e 's/(^.*?\\label{exercise-551})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-51}{})/\\newpage\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?\\label{exercise-606})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?\\label{exercise-607})/\\pagebreak\n\n\1/' orcca.tex; \
	echo 'section-equations-and-inequalities-as-true-false-statements'; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-60}{})/\\pagebreak\n\n\1/' orcca.tex; \
	echo 'section-solving-one-step-equations'; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-67}{})/\\pagebreak\n\n\1/' orcca.tex; \
	echo 'section-percentages'; \
	perl -pi -e 's/(\\begin{example}.*?\\label{example-62}\n)/\1\\leavevmode\n/' orcca.tex; \
	perl -pi -e 's/(\\begin{example}.*?\\label{example-high-school-classes}\n)/\1\\leavevmode\n/' orcca.tex; \
	perl -pi -e 's/(\\begin{example}.*?\\label{example-65}\n)/\1\\leavevmode\n/' orcca.tex; \
	perl -p0i -e 's/(\\subparagraph\[{Basic Percentage Calculation.*?\n\\begin{exercisegroup})/\1\[after-item-skip=\\dimexpr\\smallskipamount-3pt\]/' orcca.tex; \
	echo 'section-modeling-with-equations-and-inequalities'; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-77}{})/\\pagebreak\n\n\1/' orcca.tex; \
	echo 'section-simplifying-expressions'; \
	perl -pi -e 's/(^.*?solution-1096})/\\pagebreak%\n\n\1/' orcca.tex; \
	perl -pi -e 's/(\\begin{divisionexercise}\{51\}\\hypertarget{exercise-1097}{})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-89}{})/\\pagebreak\n\n\1/' orcca.tex; \
	echo 'review-variables-expressions-and-equations'; \
	perl -pi -e 's/(\\hypertarget{exercisegroup-95}{}%)/\\newpage\n\n\1/' orcca.tex; \
	perl -pi -e 's/(\\hypertarget{exercisegroup-98}{}%)/\\newpage\n\n\1/' orcca.tex; \
	echo 'section-solving-multistep-linear-equations'; \
	perl -p0i -e 's/(\\begin{namedlist}\n\\begin{namedlistcontent}\n\\leavevmode%\n\\begin{itemize}\[label=\\textbullet\]\n\\item{}\\hypertarget{p-\d+}{}%\nAn expression like)/\\pagebreak%\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^\\exercise)(\[69\.\] \\hypertarget{exercise-1285}{})/\1\*\2/' orcca.tex; \
	perl -pi -e 's/(^\\exercise)(\[70\.\] \\hypertarget{exercise-1286}{})/\1\*\2/' orcca.tex; \
	perl -p0i -e 's/\\hypertarget{p-13681}{}%\nSolve the equation\.%\n//' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-103}{})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-107}{})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-108}{})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-110}{})/\\pagebreak\n\n\1/' orcca.tex; \
	echo 'section-linear-equations-and-inequalities-with-fractions'; \
	perl -pi -e 's/(^.*?solution-1479})/\\pagebreak%\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?solution-1481})/\\pagebreak%\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?exercises-21})/\\pagebreak%\n\n\1/' orcca.tex; \
	perl -p0i -e 's/(\\hypertarget{exercisegroup-118}{}%\\hypertarget{p-\d+}{}%\n)Solve the equation\.%\n/\1/' orcca.tex; \
	perl -p0i -e 's/(\\hypertarget{exercisegroup-119}{}%\\hypertarget{p-\d+}{}%\n)Solve the equation\.%\n/\1/' orcca.tex; \
	perl -p0i -e 's/(\\hypertarget{exercisegroup-122}{}%\n\\hypertarget{p-]d+}{}%\n)Solve this inequality\.%\n/\1/' orcca.tex; \
	echo 'section-isolating-a-linear-variable'; \
	perl -p0i -e 's/(\\hypertarget{exercisegroup-126}{}%\n\\hypertarget{p-\d+}{}%\nSolve the linear equation for .*?\n\\begin{exercisegroup})/\1\[after-skip=0pt,after-item-skip=\\dimexpr\\smallskipamount-8pt\]/' orcca.tex; \
	echo 'section-ratios-and-proportions'; \
	perl -p0i -e 's/(\\subparagraph\[{Setting Up Ratios and Proportions}\].*?\n\\begin{exercisegroup})/\1\[after-item-skip=\\dimexpr\\smallskipamount-8pt\]/' orcca.tex; \
	echo 'section-special-solution-sets'; \
	perl -p0i -e 's/\\hypertarget{p-16368}{}%\nSolve the equation\.%\n//' orcca.tex; \
	perl -p0i -e 's/\\hypertarget{p-16458}{}%\nSolve this inequality\. Answer using interval notation\.%\n//' orcca.tex; \
	echo 'section-cartesian-coordinate-system'; \
	perl -pi -e 's/(Assume each unit in the grid represents one city block.%\n)/\1\\leavevmode%\n\n/' orcca.tex; \
	perl -pi -e 's/(In a Cartesian coordinate system, the map of Carl.s neighborhood would look like this:%\n)/\1\\leavevmode%\n\n/' orcca.tex; \
	perl -pi -e 's/(^.*?exercises-26})/\\pagebreak%\n\n\1/' orcca.tex; \
	perl -pi -e 's/\\href{(http:\/\/wdfw\.wa\.gov\/publications\/01793\/wdfw01793\.pdf)}{http:\/\/wdfw\.wa\.gov\/publications\/01793\/wdfw01793\.pdf}/\\url{\1}/' orcca.tex; \
	perl -pi -e 's/\\href{(http:\/\/www\.pewhispanic\.org\/2015\/09\/28\/chapter-5-u-s-foreign-born-population-trends\/)}{http:\/\/www\.pewhispanic\.org\/2015\/09\/28\/chapter-5-u-s-foreign-born-population-trends\/}/\\url{\1}/' orcca.tex; \
	perl -pi -e 's/( \(Source: \\url)/\\\\\1/' orcca.tex; \
	perl -p0i -e 's/(\\subparagraph\[{Creating Sketches of Graphs}\].*?\n\\begin{exercisegroup})/\1\[after-item-skip=\\dimexpr\\smallskipamount-8pt\]/' orcca.tex; \
	perl -p0i -e 's/(\\subparagraph\[{Regions in the Cartesian Plane}\].*?\n\\begin{exercisegroup})/\1\[after-item-skip=-1pc,after-skip=-1pc\]/' orcca.tex; \
	perl -p0i -e 's/(\\subparagraph\[{Plotting Points and Choosing a Scale}\].*?\n\\begin{exercisegroup})/\1\[after-item-skip=-1pc,after-skip=0pt\]/' orcca.tex; \
	echo 'section-graphing-equations'; \
	perl -p0i -e 's/(\\begin{exercisegroup})(\(2\)\n\\exercise\[9\.\] \\hypertarget{exercise-1722}{})/\1\[after-item-skip=\\dimexpr\\smallskipamount-7pt\]\2/' orcca.tex; \
	echo 'section-exploring-two-variable-data-and-rates-of-change'; \
	perl -pi -e 's/(^.*?\\label{exercise-1789})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -p0i -e 's/(\\hypertarget{exercisegroup-149}{}%\n.*?\n.*?\n\\begin{exercisegroup})/\1\[after-item-skip=0pt,after-skip=0pt\]/' orcca.tex; \
	perl -p0i -e 's/(\\subparagraph[{Linear Relationships}].*?\\hypertarget{exercisegroup-150}{}\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n\\begin{exercisegroup})/\1\[after-item-skip=0pt,after-skip=0pt\]/' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-151}{})/\\pagebreak\n\n\1/' orcca.tex; \
	echo 'section-slope'; \
	perl -p0i -e 's/(\\subparagraph\[{Slope and Graphs}\]{\\hspace{-1em}Slope and Graphs}\\hypertarget{exercisegroup-154}{}\n\\begin{exercisegroup})/\1\[after-item-skip=\\dimexpr\\smallskipamount-8pt,after-skip=\\dimexpr\\smallskipamount-8pt\]/' orcca.tex; \
	perl -p0i -e 's/(\\begin{multicols}\{3\}\n\\begin{enumerate}\[label=\\alph\*\.\]\n\\item\\hypertarget{li-\d+}{}\\hypertarget{p-\d+}{}%\nThe first segment has slope  \\fillin\{10\}\.%)/\\vspace{-4pc}%\n\n\1/' orcca.tex; \
	perl -pi -e 's/^ \\fillin{\d+}%/%/g' orcca.tex; \
	perl -pi -e 's/(^.*?\\label{exercise-1790})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-154}{})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?\\label{exercise-1849})/\\leavevmode\n\n\1/' orcca.tex; \
	perl -pi -e 's/(\\subparagraph\[{Challenge}\]{\\hspace{-1em}Challenge}\\hypertarget{exercisegroup-157}{})/\\vspace{-2.5pc}\n\n\1/' orcca.tex; \
	echo 'section-slope-intercept-form'; \
	perl -pi -e 's/(However, the rates of change are calculated as follows:)\\leavevmode%/\1/' orcca.tex; \
	perl -p0i -e 's/(\\begin{equation\*}\n\\frac{\\Delta y}{\\Delta x}=\\frac{41000-27500})/\\vspace{-2\.5pc}\n\n\1/' orcca.tex; \
	perl -p0i -e 's/(\\begin{equation\*}\ny=3\.85)/\\vspace{-1pc}\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-160}{})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -p0i -e 's/(\\subparagraph\[{Writing a Slope-Intercept Equation Given Two Points}\].*?\\hypertarget{exercisegroup-163}{}\n\\begin{exercisegroup})/\\vspace{-2pc}\n\n\1\[after-item-skip=-1pc\]/' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-165}{})/\\pagebreak\n\n\1/' orcca.tex; \
	echo 'section-point-slope-form'; \
	perl -pi -e 's/(^.*?\\label{exercise-point-slope})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{solution-2114}{})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-167}{})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -p0i -e 's/(^.*?\\hypertarget{exercisegroup-169}{}\n.*?\n.*?\n.*?\n\\begin{exercisegroup})/\\pagebreak\n\n\1\[after-item-skip=-2pc\]/' orcca.tex; \
	echo 'section-standard-from'; \
	perl -pi -e 's/(^.*?\\label{exercises-32})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -p0i -e 's/(.*?\\hypertarget{exercisegroup-176}{}\n\\begin{exercisegroup})/\1\[after-item-skip=-1pc\]/' orcca.tex; \
	echo 'section-horizontal-vertical-parallel-and-perpendicular-lines'; \
	perl -pi -e 's/(.*?\\hypertarget{paragraphs-45}{}\n)/\1\\leavevmode%\n/' orcca.tex; \
	perl -p0i -e 's/(.*?\\hypertarget{exercisegroup-180}{}\n\\begin{exercisegroup})/\1\[after-item-skip=-1pc,after-skip=-1pc\]/' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-184}{})/\\pagebreak\n\n\1/' orcca.tex; \
	echo 'review-graphing-lines'; \
	perl -pi -e 's/(^.*?\\hypertarget{solution-2340}{})/\\pagebreak\n\n\1/' orcca.tex; \
	echo 'section-solving-systems-of-linear-equations-by-graphing'; \
	perl -pi -e 's/(\\begin{remark}\\label{remark-35})/\\pagebreak%\n\n\1/' orcca.tex; \
	perl -p0i -e 's/(\\begin{example}\\label{example-solving-systems-by-graphing-intro}\n)/\1\\leavevmode%\n\n/' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-201}{})/\\pagebreak\n\n\1/' orcca.tex; \
	echo 'section-elimination'; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-209}{})/\\pagebreak\n\n\1/' orcca.tex; \
	echo 'review-systems-of-linear-equations'; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-213}{})/\\pagebreak\n\n\1/' orcca.tex; \
	echo 'section-exponent-rules'; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-220}{})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-222}{})/\\pagebreak\n\n\1/' orcca.tex; \
	echo 'section-adding-and-subtracting-polynomials'; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-233}{})/\\pagebreak\n\n\1/' orcca.tex; \
	echo 'section-multiplying-polynomials'; \
	echo 'section-special-cases-of-multiplying-polynomials'; \
	perl -pi -e 's/(^.*?\\hypertarget{solution-3065}{})/\\pagebreak\n\n\1/' orcca.tex; \
	echo 'section-factoring-trinomials-with-leading-coefficient-one'; \
	perl -p0i -e 's/(.*?\\hypertarget{exercisegroup-280}{}\n\\par%\n.*?\n.*?\n\\begin{exercisegroup})/\1\[after-skip=-1pc\]/' orcca.tex; \
	perl -p0i -e 's/(.*?\\hypertarget{exercisegroup-281}{}\n\\par%\n.*?\n.*?\n\\begin{exercisegroup})/\1\[after-skip=-1pc\]/' orcca.tex; \
	echo 'section-factoring-special-patterns'; \
	perl -p0i -e 's/(\\hypertarget{p-\d+}{}%\nTo use these formulas effectively,)/\\leavevmode\n\n\1/' orcca.tex; \
	echo 'section-factoring-strategies'; \
	perl -pi -e 's/(^.*?\\label{exercises-53})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-290}{})/\\pagebreak\n\n\1/' orcca.tex; \
	echo 'section-square-root-properties'; \
	perl -pi -e 's/(^.*?\\label{exercises-56})/\\pagebreak\n\n\1/' orcca.tex; \
	echo 'section-the-quadratic-formula'; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-318}{})/\\pagebreak\n\n\1/' orcca.tex; \
	echo 'section-complex-solutions-to-quadratic-equations'; \
	perl -pi -e 's/(^.*?\\label{subsection-203})/\\pagebreak%\n\n\1/' orcca.tex; \
	echo 'section-strategies-for-solving-quadratic-equations'; \
	echo 'review-solving-quadratic-equations'; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-328}{})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -p0i -e 's/(.*?\\hypertarget{exercisegroup-340}{}\n\\par%\n.*?\n.*?\n\\begin{exercisegroup})/\1\[after-item-skip=-1pc\]/' orcca.tex; \
	echo 'section-introduction-to-functions'; \
	perl -pi -e 's/(^.*?\\hypertarget{solution-4496}{})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-342}{})/\\pagebreak%\n\n\1/' orcca.tex; \
	perl -p0i -e 's/(\\exercise!\[13\.\] \\hypertarget{exercise-4087}{}\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n)/\1\\vspace{-1.5pc}/' orcca.tex; \
	perl -p0i -e 's/(\\exercise!\[14\.\] \\hypertarget{exercise-4088}{}\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n)/\1\\vspace{-1.5pc}/' orcca.tex; \
	perl -p0i -e 's/\\par\n(\\hypertarget{p-\d+}{}%\nThis function has domain)/\\vspace{-1\.5pc}\n\n\1/g' orcca.tex; \
	perl -p0i -e 's/(\\end{sidebyside}\n)(\\hypertarget{p-38[56]\d+}{}%\n\\begin{enumerate})/\1\\vspace{-1.5pc}\n\n\2/g' orcca.tex; \
	perl -pi -e 's/(\\includegraphics\[width=1\\linewidth)(\]{images\/webwork-39[78][1234567890]-image-1\.png})/\1,height=0.95\\linewidth\2/g' orcca.tex; \
	perl -p0i -e 's/(\\subparagraph\[{Functions Represented with Graphs}\].*?\\hypertarget{exercisegroup-345}{}\n\\begin{exercisegroup})/\1\[after-item-skip=-0.5pc\]/' orcca.tex; \
	perl -pi -e 's/(The function ..C.. models the the number of customers in a store since the store opened on a certain day, where ..t.. stands for the number of hours since the store opened\.%)/\\pagebreak%\n\n\1/' orcca.tex; \
	echo 'section-properties-of-quadratic-functions'; \
	perl -pi -e 's/(^.*?\\hypertarget{solution-4578}{})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?\\label{exercises-63})/\\newpage\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-355}{})/\\pagebreak%\n\n\1/' orcca.tex; \
	echo 'section-graphing-quadratic-functions'; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-359}{})/\\pagebreak%\n\n\1/' orcca.tex; \
	echo 'review-graphs-of-quadratic-functions'; \
	perl -pi -e 's/(\\begin{example}.*?\\label{example-48[567]}\n)/\1\\leavevmode\n/g' orcca.tex; \
	perl -pi -e 's/(\\begin{example}.*?\\label{example-490}\n)/\1\\leavevmode\n/g' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{solution-4727}{})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -p0i -e 's/(\\end{sidebyside}\n)\\par\n(\\hypertarget{p-\d+}{}%\n\\leavevmode%\n\\begin{multicols}\{)/\1\\vspace{-1pc}\n\n\2/g' orcca.tex; \
	perl -pi -e 's/(^.*?\\label{exercises-65})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -p0i -e 's/(\\exercise!\[1\.\] \\hypertarget{exercise-4282}{}\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n)/\1\\vspace{-1.5pc}\n\n/' orcca.tex; \
	perl -p0i -e 's/(\\exercise!\[2\.\] \\hypertarget{exercise-4283}{}\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n)/\1\\vspace{-1.5pc}\n\n/' orcca.tex; \
	perl -pi -e 's/(.*\\hypertarget{exercise-4283}{})/\\vspace{-1.5pc}\n\n\1/' orcca.tex; \
	perl -pi -e 's/(.*\\hypertarget{exercise-4284}{})/\\vspace{-1.5pc}\n\n\1/' orcca.tex; \
	perl -pi -e 's/(^.*?\\hypertarget{exercisegroup-363}{})/\\pagebreak\n\n\1/' orcca.tex; \
	perl -p0i -e 's/(\\exercise\[(19|20)\.\].*?\n.*?\n.*?\n.*?\n.*?\n.*?\n\\begin{tabular}{lllllllll}\n.*?\n.*?\n.*?\n)\\par(}\n.*?\n.*?\n.*?\n.*?\n)/\1\3\\vspace{-1\.5pc}\n\n/g' orcca.tex; \
	xelatex orcca.tex; \
	xelatex orcca.tex; \
	xelatex orcca.tex

#  HTML output
#  Output lands in the subdirectory:  $(HTMLOUT)
html:
	install -d $(OUTPUT)
	install -d $(HTMLOUT)
	-rm $(HTMLOUT)/*.html
	-rm -r $(HTMLOUT)/knowl
	-rm -r $(HTMLOUT)/images
	install -d $(HTMLOUT)/images
	cp -a $(IMAGESOUT) $(HTMLOUT)
	cp -a $(IMAGESSRC) $(HTMLOUT)
# 	cp -a $(WWOUT)/*.png $(HTMLOUT)/images/
	cd $(WWOUT); \
	rsync -r --include='*.png' --exclude='*' . $(HTMLOUT)/images
	cp $(CSS) $(HTMLOUT)
	cd $(HTMLOUT); \
	xsltproc -xinclude --stringparam publisher $(PUBFILE) --stringparam exercise.inline.hint no --stringparam exercise.inline.answer no --stringparam exercise.inline.solution yes --stringparam exercise.divisional.hint no --stringparam exercise.divisional.answer no --stringparam exercise.divisional.solution no --stringparam html.knowl.exercise.inline no --stringparam html.knowl.example no --stringparam html.css.extra orcca.css $(PRJXSL)/orcca-html.xsl $(MAINFILE)

# make all the image files in svg format
laneimages:
	install -d $(OUTPUT)
	install -d $(IMAGESOUT)
	-rm $(IMAGESOUT)/*.svg
	$(MB)/pretext/pretext -vv -c latex-image -p $(PUBFILE) -f svg -d $(IMAGESOUT) $(MAINFILE)
#	$(MB)/pretext/pretext -c asymptote -f svg -d $(IMAGESOUT) $(OUTPUT)/merge.xml

# run this to scrape thumbnail images from YouTube for any YouTube videos
youtube:
	install -d $(OUTPUT)
	install -d $(IMAGESOUT)
	-rm $(IMAGESOUT)/*.jpg
	$(MB)/pretext/pretext -c youtube -d $(IMAGESOUT) $(MAINFILE)


###########
# Utilities
###########

# Verify Source integrity
#   Leaves "dtderrors.txt" in OUTPUT
#   can then grep on, e.g.
#     "element XXX:"
#     "does not follow"
#     "Element XXXX content does not follow"
#     "No declaration for"
#   Automatically invokes the "less" pager, could configure as $(PAGER)
check:
	install -d $(OUTPUT)
	-rm $(OUTPUT)/jingreport.txt
	-java -classpath ~/jing-trang/build -Dorg.apache.xerces.xni.parser.XMLParserConfiguration=org.apache.xerces.parsers.XIncludeParserConfiguration -jar ~/jing-trang/build/jing.jar $(MB)/schema/pretext.rng $(MAINFILE) > $(OUTPUT)/jingreport.txt
	perl -pi -e 's/^.*permid.*\n//g' $(OUTPUT)/jingreport.txt
	less $(OUTPUT)/jingreport.txt

gource:
	install -d $(OUTPUT)
	-rm $(OUTPUT)/gource.mp4
	-gource --user-filter 'Stephen Simonds' --title ORCCA --key --background-image src/images/orca3.png --user-image-dir .git/avatar/ --hide filenames --seconds-per-day 0.2 --auto-skip-seconds 1 -1280x720 -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libx264 -preset veryslow -pix_fmt yuv420p -crf 23 -threads 0 -bf 0 $(OUTPUT)/gource.mp4
	-mv gource.mp4 $(OUTPUT)/gource.mp4

